[HWORKS-225] Hopsworks ha
logicalclocks/hopsmonitor-chef pull request #130
Opened 2023-05-17 07:38 UTC by ErmiasG

2023-05-17 08:17 UTC, o-alex approved these changes

2023-05-21 17:38 UTC, SirOibaf reviewed
I think this is a bad idea. I would prefer if we had `0.alertmanager.service.consul` or something like this to identify the different nodes. 

Having IP hardcoded in the configuration and systemd unit files will make it extra hard to implement upgrades and similar, especially on the cloud.

2023-05-22 11:18 UTC, kouzant commented
@ErmiasG @SirOibaf I was reading the documentation for `--cluster.peer` parameter of alertmanager and indeed they say it should be one per peer.
Nevertheless I checked the code and they resolve the domain name and use all the IP addresses https://github.com/prometheus/alertmanager/blob/v0.17.0/cluster/cluster.go#L675

Next I thought that this won't work because when alertmanager 0 starts, alertmanager  1 might not be up yet so the domain resolution will not return the correct hosts. But it appears they refresh the peers periodically https://github.com/prometheus/alertmanager/blob/v0.17.0/cluster/cluster.go#L246

Now the only problem is that the resolved peers might also contain itself. If they filter the local agent that would not be a problem, otherwise this solution will not work. It is worth trying though

2023-05-22 11:44 UTC, kouzant requested changes

2023-05-22 11:44 UTC, kouzant commented on templates/default/prometheus.yml.erb
> +    - targets:
For Prometheus `alertmanagers` configuration I think the `static_configs` is not suitable anymore. According to the documentation you can use `consul_sd_configs` the same way we do for scraping

2023-05-23 10:16 UTC, kouzant approved these changes

2023-05-23 11:07 UTC, merged