[HOPSWORKS-2356] alerting
logicalclocks/hopsmonitor-chef pull request #71
Opened 2021-05-05 11:25 UTC by ErmiasG

2021-05-05 17:29 UTC, ErmiasG commented
logicalclocks/hops-testing-ee/pull/333

2021-05-11 10:05 UTC, SirOibaf requested changes

2021-05-11 10:05 UTC, SirOibaf commented on files/default/templates/hopsworks.email.tmpl
> +                      {{ if .Labels.featureGroupId -}} <li>  Feature Group id: {{ .Labels.featureGroupId }} </li> {{ end }}
Feature group id is useless. The alert should contain feature store name/ feature group name/feature group version.

2021-05-11 10:05 UTC, SirOibaf commented on files/default/templates/hopsworks.email.tmpl
> +                      {{ if .Labels.featureGroupId -}} <li>  Feature Group id: {{ .Labels.featureGroupId }} </li> {{ end }}
Feature group id is useless. The alert should contain feature store name/ feature group name/feature group version.

2021-05-11 10:05 UTC, SirOibaf commented on files/default/templates/hopsworks.slack.tmpl
> +      - *Feature group id:* {{ .Labels.featureGroupId }}
Feature group id is useless. The alert should contain feature store name/ feature group name/feature group version.

2021-05-17 07:43 UTC, SirOibaf approved these changes

2021-05-17 07:49 UTC, merged