[HOPSWORKS-2978] Knative and Kserving metrics
logicalclocks/hopsmonitor-chef pull request #85
Opened 2022-03-02 08:53 UTC by gibchikafa

2022-03-02 20:17 UTC, jimdowling requested changes
Couple of small changes.

2022-03-02 20:17 UTC, jimdowling commented on attributes/default.rb
> +default['hopsmonitor']['kube_ca'] = "#{node['certs']['dir']}/kube/kube-ca.cert.pem"
Small thing, but please use spaces to align all of the   = "...." in the file.
See lines 90-93 for example.

2022-03-02 20:17 UTC, jimdowling commented on attributes/default.rb
> +default['cloud']['metrics']['port']                      = "9096"
You are missing at the top of attributes/default.rb (add in line 7)
include_attribute "kube-hops"

If you don't include this, the attributes in lines 95-98 might not find the correct prometheus/root_dir attribute.

2022-03-02 20:17 UTC, jimdowling commented on files/default/dashboards/kserving/knative_control_plane_efficiency.json
> +{
I have no idea, assume this file is correct.

2022-03-02 20:17 UTC, jimdowling commented on recipes/grafana.rb
> +directory "#{node['grafana']['base_dir']}/conf/provisioning/dashboards/kserving" do
Can you call the directory "kserve" not "kserving"? Both this and the remote directory copied in.

2022-03-02 20:17 UTC, jimdowling commented on recipes/prometheus.rb
> +      'kube_master_ip' => kube_cluster_master_ip,
Remove trailing comma - ','

2022-03-02 20:17 UTC, jimdowling commented on templates/default/dashboards_provisioning.yml.erb
> +    path: /srv/hops/grafana/conf/provisioning/dashboards/kserving
kserve

2022-03-02 20:17 UTC, jimdowling commented on templates/default/prometheus.yml.erb
> +<% end -%>
Chef code looks ok here.

2022-03-04 12:35 UTC, jimdowling commented
In Karamelfile, 
add the global dependency to 
recipe: hopsmon::prometheus
    global:
 - kube-hops::hopsmon
 - kabent::default

2022-04-06 13:23 UTC, jimdowling approved these changes

2022-04-06 13:23 UTC, jimdowling commented on recipes/prometheus.rb
> +    only_if { node['install']['kubernetes'] == 'true' }
remove

2022-04-08 12:13 UTC, SirOibaf submitted a review, later dismissed

2022-04-08 12:13 UTC, SirOibaf commented on Berksfile
> +cookbook 'kube-hops', github: "gibchikafa/kube-hops-chef", branch: "HOPSWORKS-2978"
@gibchikafa - this is still a problem

2022-04-22 11:41 UTC, jimdowling commented on attributes/default.rb
> +default['cloud']['metrics']['port']                      = "9096"
Attributes were moved from kube-hops here, no longer relevant.

2022-04-22 11:42 UTC, jimdowling approved these changes

2022-04-22 11:43 UTC, merged